### ISSUE TITLE
Implement a Transport based on OkHttp

### ISSUE THREAD

**Issue by sschuberth** [sonatype/ossindex-public#7]
[OkHttp](https://github.com/square/okhttp) is a very popular HTTP library. As it's likely already in use in a user's dependency stack, it would be nice to have a `Transport` implementation that uses OkHttp so that such users don't need to introduce a dependency on another HTTP library.

**Comment by sschuberth** [comment]
Are there any plans to work on this from your side @ndonewar or @jdillon?

**Comment by jdillon** [comment]
@sschuberth I have no plans to do so do not know about @ndonewar and the OSSIndex team however.

It its pretty simple (last I recall) to implement a transport impl, then interface only has 2 methods:

https://github.com/sonatype/ossindex-public/blob/master/client/src/main/java/org/sonatype/ossindex/service/client/transport/Transport.java

I would expect if a user preferred to use OkHttp-impl instead of the provided Apache HttpClient or HttpUrlConnection implementations they would implement this as they need.

If you want to avoid any extra HTTP library you can exclude the httpclient dependencies and use the HttpUrlConnection transport.

**Comment by ndonewar** [comment]
Hi @sschuberth - we have no plans at this time.

**Comment by sschuberth** [comment]
I'm closing this in favor of the OkHttp / Retrofit based client we now have at https://github.com/oss-review-toolkit/ort/tree/main/clients/oss-index.
